import type { SatMatrixRule, SatRuleModule, SatRuleCoverage, SatRuleSource } from "./sat-matrix.types.js";

export const CFDI40_MATRIX_RULES: SatMatrixRule[] = [
  // A) CFDI Base
  {
    id: "A1",
    source: "CFDI40_ANEXO20",
    officialField: "Version",
    officialDescription: "Versión debe ser 4.0",
    module: "CFDI_BASE",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CFDI_VERSION_INCONSISTENT_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["IS) CFDI 3.3 con campos 4.0"],
  },
  {
    id: "A2",
    source: "CFDI40_ANEXO20",
    officialField: "TipoDeComprobante",
    officialDescription: "Tipo de comprobante debe ser I, E, T, N, P, o M",
    module: "CFDI_BASE",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CATALOG_TIPO_COMPROBANTE_UNKNOWN_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["A) CFDI 4.0 Ingreso válido básico"],
  },
  {
    id: "A3",
    source: "CFDI40_ANEXO20",
    officialField: "Moneda",
    officialDescription: "Moneda debe ser código ISO 4217 válido",
    module: "CFDI_BASE",
    coverage: "COVERED_PARTIAL",
    fiscoraFindingCodes: ["CATALOG_MONEDA_UNKNOWN_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    notes: ["Catálogo Fiscora es parcial; requiere ISO 4217 completo"],
  },
  {
    id: "A4",
    source: "CFDI40_ANEXO20",
    officialField: "TipoCambio",
    officialDescription: "TipoCambio requerido cuando Moneda != MXN",
    module: "CFDI_BASE",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["IX) Moneda USD sin TipoCambio"],
    severityAlignment: "SAME",
    testCases: ["IX) Moneda USD sin TipoCambio"],
  },
  {
    id: "A5",
    source: "CFDI40_ANEXO20",
    officialField: "Exportacion",
    officialDescription: "Exportación debe ser 01-04",
    module: "CFDI_BASE",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CATALOG_EXPORTACION_UNKNOWN_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["JB) Pago 4.0 con Exportacion distinta de 01"],
  },
  {
    id: "A6",
    source: "CFDI40_ANEXO20",
    officialField: "Subtotal",
    officialDescription: "Subtotal no debe ser negativo",
    module: "TOTALES",
    coverage: "COVERED_PARTIAL",
    fiscoraFindingCodes: [],
    severityAlignment: "NOT_MAPPED",
    notes: ["No implementado; subtotal negativo puede existir en retenciones"],
  },
  {
    id: "A7",
    source: "CFDI40_ANEXO20",
    officialField: "Total",
    officialDescription: "Total debe coincidir con subtotal + impuestos - descuento",
    module: "TOTALES",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["TOT_VS_CONCEPT_MATCH_REVIEW", "CFDI_TOTAL_WITH_CONCEPT_TAXES_RECALC_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["G) Totales inconsistente"],
  },
  {
    id: "A8",
    source: "CFDI40_ANEXO20",
    officialField: "LugarExpedicion",
    officialDescription: "LugarExpedicion debe ser código postal válido",
    module: "CFDI_BASE",
    coverage: "COVERED_HEURISTIC",
    fiscoraFindingCodes: [],
    severityAlignment: "FISCORA_STRONGER",
    notes: ["No implementado; placeholder"],
  },
  // B) Emisor/Receptor
  {
    id: "B1",
    source: "CFDI40_ANEXO20",
    officialField: "Emisor.RFC",
    officialDescription: "RFC del emisor no debe ser vacío",
    module: "EMISOR_RECEPTOR",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["EMISOR_RFC_MISSING"],
    severityAlignment: "SAME",
    testCases: ["HY) Emisor sin RFC/nombre/régimen"],
  },
  {
    id: "B2",
    source: "CFDI40_ANEXO20",
    officialField: "Receptor.RFC",
    officialDescription: "RFC del receptor no debe ser vacío",
    module: "EMISOR_RECEPTOR",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RECEPTOR_RFC_MISSING"],
    severityAlignment: "SAME",
    testCases: ["HZ) Receptor sin RFC/nombre/régimen/domicilio/UsoCFDI"],
  },
  {
    id: "B3",
    source: "CFDI40_ANEXO20",
    officialField: "Receptor.UsoCFDI",
    officialDescription: "UsoCFDI debe ser clave válida según catálogo",
    module: "EMISOR_RECEPTOR",
    coverage: "COVERED_PARTIAL",
    fiscoraFindingCodes: ["RECEPTOR_USO_CFDI_FORMAT_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    notes: ["Catálogo parcial; requiere catálogo oficial completo"],
  },
  {
    id: "B4",
    source: "CFDI40_ANEXO20",
    officialField: "Receptor.RegimenFiscalReceptor",
    officialDescription: "Régimen fiscal receptor debe ser código de 3 dígitos",
    module: "EMISOR_RECEPTOR",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RECEPTOR_REGIMEN_FISCAL_FORMAT_REVIEW"],
    severityAlignment: "SAME",
    notes: ["Formato validado; catálogo parcial"],
  },
  // C) Conceptos
  {
    id: "C1",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.ClaveProdServ",
    officialDescription: "ClaveProdServ debe ser código de 8 dígitos",
    module: "CONCEPTOS",
    coverage: "COVERED_HEURISTIC",
    fiscoraFindingCodes: ["CONCEPT_CLAVE_PROD_SERV_FORMAT_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    notes: ["Formato validado; catálogo parcial"],
  },
  {
    id: "C2",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.ClaveUnidad",
    officialDescription: "ClaveUnidad es requerida en CFDI 4.0",
    module: "CONCEPTOS",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CONCEPT_MISSING_CLAVE_UNIDAD", "CONCEPT_UNIDAD_WITHOUT_CLAVE_UNIDAD_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    notes: ["Catálogo parcial; requiere catálogo oficial"],
  },
  {
    id: "C3",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.Importe",
    officialDescription: "Importe = Cantidad × ValorUnitario (con tolerancia)",
    module: "CONCEPTOS",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CONCEPT_ROUNDING_DIFFERENCE_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["H) valueTrace se genera para mismatch numérico"],
  },
  {
    id: "C4",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.ObjetoImp",
    officialDescription: "ObjetoImp debe ser 01-08 según catálogo",
    module: "CONCEPTOS",
    coverage: "COVERED_PARTIAL",
    fiscoraFindingCodes: ["CONCEPT_OBJETO_IMP_04_08_REVIEW", "OBJETOIMP_01_WITH_GLOBAL_TAXES_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
  },
  // D) Impuestos por concepto
  {
    id: "D1",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.Impuestos.Traslado.Impuesto",
    officialDescription: "Impuesto debe ser 001 (ISR), 002 (IVA) o 003 (IEPS)",
    module: "IMPUESTOS_CONCEPTO",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CATALOG_CONCEPT_TAX_IMPUESTO_UNKNOWN_REVIEW"],
    severityAlignment: "SAME",
  },
  {
    id: "D2",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.Impuestos.Traslado.TipoFactor",
    officialDescription: "TipoFactor debe ser Tasa, Cuota o Exento",
    module: "IMPUESTOS_CONCEPTO",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CATALOG_CONCEPT_TAX_TIPO_FACTOR_UNKNOWN_REVIEW", "TAX_EXENTO_WITH_RATE_REVIEW", "TAX_RATE_NEGATIVE_REVIEW"],
    severityAlignment: "SAME",
  },
  {
    id: "D3",
    source: "CFDI40_ANEXO20",
    officialField: "Conceptos.Concepto.Impuestos.Traslado.TasaOCuota",
    officialDescription: "TasaOCuota debe ser positivo y <= 1 para Tasa",
    module: "IMPUESTOS_CONCEPTO",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["TAX_RATE_TOO_HIGH_REVIEW", "TAX_TASA_ZERO_WITH_AMOUNT_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["A6) TAX_RATE_TOO_HIGH_REVIEW"],
  },
  // E) TFD/Sellos
  {
    id: "E1",
    source: "CFDI40_ANEXO20",
    officialField: "TimbreFiscalDigital",
    officialDescription: "Debe existir TimbreFiscalDigital para CFDI timbrado",
    module: "TIMBRE_FISCAL_DIGITAL",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: [],
    severityAlignment: "NOT_MAPPED",
    requiresXsd: true,
    notes: ["TFD detectado pero sin validación XSD formal"],
  },
  {
    id: "E2",
    source: "CFDI40_ANEXO20",
    officialField: "TimbreFiscalDigital.UUID",
    officialDescription: "UUID no debe ser vacío",
    module: "TIMBRE_FISCAL_DIGITAL",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["TFD_UUID_MISSING"],
    severityAlignment: "SAME",
    testCases: ["A3) TFD_UUID_MISSING"],
  },
  {
    id: "E3",
    source: "CFDI40_MATRIZ_ERRORES",
    officialField: "TimbreFiscalDigital.FechaTimbrado",
    officialDescription: "Fecha timbrado no debe ser futura",
    module: "TIMBRE_FISCAL_DIGITAL",
    coverage: "COVERED_HEURISTIC",
    fiscoraFindingCodes: ["TFD_FECHA_TIMBRADO_FUTURE_REVIEW"],
    severityAlignment: "FISCORA_STRONGER",
  },
  {
    id: "E4",
    source: "CFDI40_MATRIZ_ERRORES",
    officialField: "Sello/SelloCFD",
    officialDescription: "Sello debe ser base64 válido y coincidir con contenido",
    module: "SELLOS_CERTIFICADOS",
    coverage: "NOT_COVERED",
    fiscoraFindingCodes: [],
    severityAlignment: "NOT_MAPPED",
    requiresCryptoValidation: true,
    notes: ["Gap crítico: validación criptográfica no implementada"],
  },
  // F) CFDI Relacionados
  {
    id: "F1",
    source: "CFDI40_ANEXO20",
    officialField: "CfdiRelacionados.TipoRelacion",
    officialDescription: "TipoRelacion debe ser código del catálogo 01-07",
    module: "CFDI_RELACIONADOS",
    coverage: "COVERED_PARTIAL",
    fiscoraFindingCodes: ["CATALOG_TIPO_RELACION_UNKNOWN_REVIEW"],
    severityAlignment: "SAME",
    requiresCatalog: true,
  },
  {
    id: "F2",
    source: "CFDI40_ANEXO20",
    officialField: "CfdiRelacionados.CfdiRelacionado.UUID",
    officialDescription: "UUID relacionado debe ser formato v4",
    module: "CFDI_RELACIONADOS",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CFDI_RELACION_UUID_FORMAT_REVIEW"],
    severityAlignment: "SAME",
    testCases: ["HX) UUID relacionado inválido"],
  },
  // G) Complemento Pago
  {
    id: "G1",
    source: "CFDI40_GUIA_LLENADO",
    officialField: "Pago20.Pago",
    officialDescription: "Tipo P debe tener complemento Pago20",
    module: "COMPLEMENTO_PAGO",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["II) Complemento Pago en Tipo I"],
    severityAlignment: "SAME",
    testCases: ["II) Complemento Pago en Tipo I"],
  },
  {
    id: "G2",
    source: "CFDI40_GUIA_LLENADO",
    officialField: "Pago20.DoctoRelacionado",
    officialDescription: "DoctoRelacionado.UUID debe ser válido",
    module: "COMPLEMENTO_PAGO",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["CFDI_RELACION_UUID_FORMAT_REVIEW"],
    severityAlignment: "SAME",
  },
  // H) Seguridad/Payload
  {
    id: "H1",
    source: "FISCORA_FORENSIC",
    officialField: "N/A",
    officialDescription: "Detección BOM UTF-8 previo al XML",
    module: "SEGURIDAD_PAYLOAD",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: [],
    severityAlignment: "NOT_MAPPED",
    notes: ["Funcionalidad Fiscora forense"],
  },
  {
    id: "H2",
    source: "FISCORA_FORENSIC",
    officialField: "N/A",
    officialDescription: "Contenido previo al XML detectado",
    module: "SEGURIDAD_PAYLOAD",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: [],
    severityAlignment: "NOT_MAPPED",
    notes: ["Funcionalidad Fiscora forense"],
  },
];

export function getMatrixRuleById(id: string): SatMatrixRule | undefined {
  return CFDI40_MATRIX_RULES.find((r) => r.id === id);
}