import type { SatMatrixRule } from "../sat-matrix.types.js";

export const PAGOS20_MATRIX_RULES: SatMatrixRule[] = [
  {
    id: "PAGOS-001",
    source: "FISCORA_FORENSIC",
    officialCode: "PAGO-01",
    officialField: "TipoDeComprobante",
    officialDescription: "Tipo P requiere complemento Pago",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_COMPLEMENT_MISSING"],
    severityAlignment: "SAME",
    testCases: ["II", "IJ"],
  },
  {
    id: "PAGOS-002",
    source: "FISCORA_FORENSIC",
    officialDescription: "Pago sin DoctoRelacionado",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_MISSING_UUID"],
    severityAlignment: "SAME",
    testCases: ["EC"],
  },
  {
    id: "PAGOS-003",
    source: "CFDI40_MATRIZ_ERRORES",
    officialField: "Pago.FechaPago",
    officialDescription: "FechaPago faltante en Pago",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_MISSING_FECHA_PAGO"],
    severityAlignment: "SAME",
    testCases: ["ED"],
  },
  {
    id: "PAGOS-004",
    source: "FISCORA_FORENSIC",
    officialDescription: "FechaPago inválida",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_FECHA_PAGO_INVALID"],
    severityAlignment: "SAME",
    testCases: ["ED"],
  },
  {
    id: "PAGOS-005",
    source: "FISCORA_FORENSIC",
    officialField: "Pago.FormaDePagoP",
    officialDescription: "FormaDePagoP faltante o desconocido",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_MISSING_FORMA_PAGO", "PAYMENT_FORMAPAGOP_UNKNOWN"],
    severityAlignment: "SAME",
    testCases: ["BF", "GG"],
  },
  {
    id: "PAGOS-006",
    source: "FISCORA_FORENSIC",
    officialField: "Pago.MonedaP",
    officialDescription: "MonedaP faltante o desconocido",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_MISSING_MONEDA", "PAYMENT_MONEDAP_UNKNOWN"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    requiredCatalogs: ["MONEDAS"],
    testCases: ["DU", "GG"],
  },
  {
    id: "PAGOS-007",
    source: "FISCORA_FORENSIC",
    officialDescription: "TipoCambioP requerido con moneda no MXN",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_MISSING_TIPO_CAMBIO"],
    severityAlignment: "SAME",
    testCases: ["DU", "IX"],
  },
  {
    id: "PAGOS-008",
    source: "FISCORA_FORENSIC",
    officialField: "Pago.Monto",
    officialDescription: "Monto no positivo en Pago",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_AMOUNT_NON_POSITIVE"],
    severityAlignment: "SAME",
  },
  {
    id: "PAGOS-009",
    source: "FISCORA_FORENSIC",
    officialDescription: "DoctoRelacionado sin IdDocumento válido",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_MISSING_ID", "RELATED_DOCUMENT_UUID_INVALID"],
    severityAlignment: "SAME",
    testCases: ["EG", "HQ"],
  },
  {
    id: "PAGOS-010",
    source: "FISCORA_FORENSIC",
    officialDescription: "MonedaDR faltante o desconocida",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_MISSING_MONEDA", "RELATED_DOCUMENT_MONEDADR_UNKNOWN"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    requiredCatalogs: ["MONEDAS"],
  },
  {
    id: "PAGOS-011",
    source: "FISCORA_FORENSIC",
    officialDescription: "EquivalenciaDR requerida con moneda",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_MISSING_EQUIVALENCIA"],
    severityAlignment: "SAME",
    testCases: ["U"],
  },
  {
    id: "PAGOS-012",
    source: "FISCORA_FORENSIC",
    officialField: "DoctoRelacionado.NumParcialidad",
    officialDescription: "NumParcialidad no positivo o faltante",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_PARTIALITY_INVALID", "RELATED_DOCUMENT_PARTIALITY_MISSING"],
    severityAlignment: "SAME",
    testCases: ["EH"],
  },
  {
    id: "PAGOS-013",
    source: "FISCORA_FORENSIC",
    officialDescription: "ImpSaldoAnt faltante o no positivo",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_BALANCE_PREVIOUS_MISSING", "RELATED_DOCUMENT_BALANCE_PREVIOUS_INVALID"],
    severityAlignment: "SAME",
  },
  {
    id: "PAGOS-014",
    source: "FISCORA_FORENSIC",
    officialDescription: "ImpPagado faltante o no positivo",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_PAID_MISSING", "RELATED_DOCUMENT_PAID_INVALID"],
    severityAlignment: "SAME",
  },
  {
    id: "PAGOS-015",
    source: "FISCORA_FORENSIC",
    officialDescription: "ImpSaldoInsoluto negativo or mismatch",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_BALANCE_NEGATIVE", "RELATED_DOCUMENT_BALANCE_MISMATCH"],
    severityAlignment: "SAME",
    testCases: ["S"],
  },
  {
    id: "PAGOS-016",
    source: "FISCORA_FORENSIC",
    officialDescription: "ImpPagado excede saldo anterior",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_PAID_EXCEEDS_PREVIOUS_BALANCE"],
    severityAlignment: "SAME",
    testCases: ["S"],
  },
  {
    id: "PAGOS-017",
    source: "FISCORA_FORENSIC",
    officialDescription: "Suma documentos pagados excede monto pago",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_TOTAL_RELATED_PAID_EXCEEDS_PAYMENT_AMOUNT"],
    severityAlignment: "SAME",
    testCases: ["T"],
  },
  {
    id: "PAGOS-018",
    source: "FISCORA_FORENSIC",
    officialField: "DoctoRelacionado.ObjetoImpDR",
    officialDescription: "ObjetoImpDR faltante o desconocido",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_OBJETOIDR_MISSING", "RELATED_DOCUMENT_OBJETOIDR_UNKNOWN"],
    severityAlignment: "SAME",
    requiresCatalog: true,
    requiredCatalogs: ["OBJETO_IMP"],
    testCases: ["EI"],
  },
  {
    id: "PAGOS-019",
    source: "FISCORA_FORENSIC",
    officialDescription: "ImpuestosDR inconsistentes",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["RELATED_DOCUMENT_TAXES_MISMATCH"],
    severityAlignment: "SAME",
    testCases: ["EJ"],
  },
  {
    id: "PAGOS-020",
    source: "FISCORA_FORENSIC",
    officialDescription: "Totales del complemento mismatch",
    module: "COMPLEMENTO_PAGO",
    complementKey: "PAGOS_20",
    coverage: "COVERED_DIRECT",
    fiscoraFindingCodes: ["PAYMENT_TOTAL_MISMATCH"],
    severityAlignment: "SAME",
    testCases: ["EK"],
  },
];